### PR TITLE
Add functionality to read email from url

### PR DESCRIPTION
**Pull request by mnbeh**

### CODE REVIEW

**Comment by pavelzubov** [comment]
The problem is actual, `token` is the required argument of confirmThreeStepAuth still))

**Comment by pavelzubov** [comment]
Let's try again, `token` is the required in confirmThreeStepAuth still 😂😂😂

**Comment by mnbeh** [comment]
Do i need to tell backend to add optional token in the method?

**Comment by pavelzubov** [comment]
Try don't remove `token` checking in https://github.com/GenesisVision/web-client/pull/1825/files#diff-b24af3ab6629339d8b750f22706fe3fc722d1d77017817f7764437c097680312R42 )

**Comment by mnbeh** [comment]
I've changed it for the case when user tries to send confirmThreeStepAuth method from email letter in different browser. It won't have a token.

**Comment by pavelzubov** [comment]
What happens if invoke /v2.0/auth/3fa/confirm with a body without the token?

**Comment by mnbeh** [comment]
204 with empty body. And this is what i need

**Comment by pavelzubov** [comment]
Than change confirmThreeStepAuth type declaration. The token in it is not optional

**Comment by mnbeh** [comment]
I've tried to change type declaration in confirmThreeStepAuth, but editor underscored it like an error.
This is the type declared on backend:

export interface ThreeFactorAuthenticatorConfirm {
    email: string;
    code: string;
    token: string;
}.

Should i tell the backend to make token an optional parameter?

**Comment by pavelzubov** [comment]
Try, but it seems they cannot. You can use a non-null assertion, "as" assertion or an empty string.

**Comment by mnbeh** [comment]
I don't get it. Where should i use it?

**Comment by pavelzubov** [comment]
In confirmThreeStepAuth.
The error is here, right?
image

**Comment by mnbeh** [comment]
I've tried to write an exclamation mark after the token, and it had showed me the following message: 
"A definite assignment assertion '!' is not permitted in this context."

**Comment by pavelzubov** [comment]
Show code)

**Comment by mnbeh** [comment]
Screenshot 2021-01-25 at 11 15 56
It hasn't changed since the last commit. But here is the photo.

**Comment by pavelzubov** [comment]
Yes, it doesn't work)) See how to use a non-null assertion)

**Comment by mnbeh** [comment]
I don't know what to do. But i really don't understand why i should change something, because token always will be a string.

**Comment by pavelzubov** [comment]
> I don't know what to do

May be `token: token!`?))

> token always will be a string.

Before you say:

> It won't have a token.

Decide, will token always be a string or not

**Pull request merged**
