### PR TITLE
Task/gv 1194 hide scrollbar tabs

### PR DESCRIPTION
**Pull request by Anchello**

### CODE REVIEW

**Comment by pavelzubov** [comment]
May be we can add one class with common styles for all tabs?

**Comment by Anchello** [comment]
> May be we can add one class with common styles for all tabs?

Added the appropriate prop and class in GVTabs

**Comment by pavelzubov** [comment]
Maybe the GVTabs will scroll if a content larger than a width and we can use the GVTabs without hasScroll flag?

**Comment by Anchello** [comment]
> Maybe the GVTabs will scroll if a content larger than a width and we can use the GVTabs without hasScroll flag?

Done

**Pull request merged**
